### ISSUE TITLE
   RelatedObjectDoesNotExist Error on User Login

### ISSUE THREAD

**Issue by stephencoduor** [nyaruka/rapidpro-docker#2]
## Description
   I am encountering a `RelatedObjectDoesNotExist` error when trying to log in as a user in the RapidPro application.

   ## Environment
   - **Request Method**: POST
   - **Request URL**: http://mydomain.info/users/login/
   - **Django Version**: 5.1
   - **Python Version**: 3.11.10
   - **Installed Applications**: 
     ```
     ('django.contrib.auth',
      'django.contrib.contenttypes',
      'django.contrib.sessions',
      'django.contrib.sites',
      'django.contrib.messages',
      'django.contrib.staticfiles',
      'django.contrib.humanize',
      'django.contrib.gis',
      'django.contrib.sitemaps',
      'django.contrib.postgres',
      'django.forms',
      'formtools',
      'imagekit',
      'redis',
      'rest_framework',
      'rest_framework.authtoken',
      'compressor',
      'smartmin',
      'smartmin.csv_imports',
      'smartmin.users',
      'timezone_field',
      'temba.apks',
      'temba.archives',
      'temba.auth_tweaks',
      'temba.api',
      'temba.request_logs',
      'temba.classifiers',
      'temba.dashboard',
      'temba.globals',
      'temba.public',
      'temba.schedules',
      'temba.templates',
      'temba.orgs',
      'temba.contacts',
      'temba.channels',
      'temba.msgs',
      'temba.notifications',
      'temba.flows',
      'temba.tickets',
      'temba.triggers',
      'temba.utils',
      'temba.campaigns',
      'temba.ivr',
      'temba.locations',
      'temba.airtime',
      'temba.sql',
      'storages')
     ```
   - **Installed Middleware**:
     ```
     ('temba.middleware.ExceptionMiddleware',
      'django.middleware.security.SecurityMiddleware',
      'django.contrib.sessions.middleware.SessionMiddleware',
      'django.middleware.common.CommonMiddleware',
      'django.middleware.csrf.CsrfViewMiddleware',
      'django.contrib.auth.middleware.AuthenticationMiddleware',
      'django.contrib.messages.middleware.MessageMiddleware',
      'django.middleware.clickjacking.XFrameOptionsMiddleware',
      'temba.middleware.OrgMiddleware',
      'temba.middleware.LanguageMiddleware',
      'temba.middleware.TimezoneMiddleware',
      'temba.middleware.ToastMiddleware')
     ```
   ## Traceback
   
   
   
   ## Steps to Reproduce
   1. Create a superuser using the command:
      ```
         sudo docker-compose exec rapidpro poetry run python manage.py shell
         #Then inside the shell I am running below commands
            from django.contrib.auth.models import User 
            User.objects.create_superuser('super_admin', 'email@example.com', 'tembaAdmin')
      ```
   2. Attempt to log in with the created superuser credentials.

   ## Expected Behavior
   The user should be able to log in without encountering an error.

   ## Actual Behavior
   The application raises a `RelatedObjectDoesNotExist` error indicating that the user has no settings.

   ## Additional Information
   I have verified that the user exists in the database, but it seems that the related user settings are not being created automatically.
   
   I have tested with Rapidpro version v9.2.5 and v9.3.54  (https://github.com/nyaruka/rapidpro/releases/tag/)

   Thank you for your assistance!

**Comment by norkans7** [comment]
You should use the signup URL to create a user

**Comment by stephencoduor** [comment]
Thanks @norkans7 but doe it work for creating a superuser. I want to create a superuser
`$ python manage.py createsuperuser`

**Comment by norkans7** [comment]
No, the superuser is not the right way to use the application.
